### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by coolsquid** [TehNut/LaunchGui#1]
Deleting the update checker file makes the GUI run in a loop. The GUI will continue to show up whenever you click the continue button.

Log: https://gist.github.com/coolsquid/b77ab2ce828def876ba0

**Comment by TehNut** [comment]
Latest builds _should_ fix it. Or at least, I was unable to reproduce afterwards.

**Comment by coolsquid** [comment]
That seems to have fixed the issue.
