### ISSUE TITLE
Crash Issue - Something With Fluid Maybe

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TehNut/LaunchGui#4]
https://gist.github.com/DPxKnightxZero/a4edaf2961183cdf619e - Crash Log.

**Comment by TehNut** [comment]
Fixed with e68a9c64acbdc1bb4ca8e369d0888ec32d8181ff. I removed something I shouldn't have while doing some minor cleanup. New build will be up within the next 10 minutes or so.

**Comment by TehNut** [comment]
I'm actually quite curious where you got the idea that it was due to Fluids from...
