### ISSUE TITLE
@playername

### ISSUE THREAD

**Issue by gravestristen** [TehNut/LaunchGui#6]
is there any way to make it say something like "Hello player name and welcome to the official shipraidsmc mod pack!" replacing player name with the user that has launched minecraft?

**Comment by TehNut** [comment]
I'm not entirely sure if I can even get the name of the player at that point, but I'll take a look.

**Comment by gravestristen** [comment]
alright thank you!

**Comment by gravestristen** [comment]
omg thank you!

**Comment by TehNut** [comment]
Build running now

**Comment by gravestristen** [comment]
you just added it?!

**Comment by TehNut** [comment]
[Yes](http://minecraft.curseforge.com/mc-mods/228810-launchgui/files/2238262)

**Comment by gravestristen** [comment]
can you port this update to 1.8?

**Comment by TehNut** [comment]
Later tonight

**Comment by gravestristen** [comment]
thank you.

**Comment by TehNut** [comment]
Done. Build completed. Pending review on CurseForge.
