### ISSUE TITLE
Version.txt missing

### ISSUE THREAD

**Issue by Ionaru** [TehNut/LaunchGui#7]
Heya

The version.txt as linked to in the LaunchGUI config appears to be missing.

Link: https://raw.githubusercontent.com/TehNut/LaunchGui/1.7.10/version.txt

**Comment by TehNut** [comment]
This isn't really an issue as it was just an example. Just make a `.txt` and put your version in it.

**Comment by Ionaru** [comment]
Yes I realise it's meant as an example, but since the config links to the file I thought I'd mention it. ;)
